# Build stage
FROM golang:1.21-alpine AS build

WORKDIR /app

RUN apk add --no-cache git

COPY main.go ./

RUN go mod init iec104-master && \
    go get github.com/juanjorosendo/go-iecp5@v0.0.1 && \
    go get github.com/sirupsen/logrus@v1.9.3 && \
    go get gopkg.in/yaml.v3@v3.0.1

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o master ./main.go

# Final stage (static binary)
FROM scratch

WORKDIR /app

COPY --from=build /app/master /app/master

ENTRYPOINT ["/app/master"]
