networks:
  icscommemulator:
    ipam:
      config:
      - subnet: 192.168.2.0/24
    name: icscommemulator
services:
  modbus_master_0:
    build:
      context: ./protocols/modbus/master
      dockerfile: Dockerfile.master
    container_name: modbus_master_container_0
    depends_on:
      modbus_slave_0:
        condition: service_healthy
      modbus_slave_1:
        condition: service_healthy
      modbus_slave_2:
        condition: service_healthy
      modbus_slave_3:
        condition: service_healthy
      modbus_slave_4:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    expose:
    - '502'
    image: modbus_master_image
    networks:
      icscommemulator:
        ipv4_address: 192.168.2.2
    volumes:
    - /tmp/ICSCommEmulator/masters/0/master.csv:/app/master.csv:ro
  modbus_master_1:
    build:
      context: ./protocols/modbus/master
      dockerfile: Dockerfile.master
    container_name: modbus_master_container_1
    depends_on:
      modbus_slave_0:
        condition: service_healthy
      modbus_slave_1:
        condition: service_healthy
      modbus_slave_2:
        condition: service_healthy
      modbus_slave_3:
        condition: service_healthy
      modbus_slave_4:
        condition: service_healthy
    environment:
    - PYTHONUNBUFFERED=1
    expose:
    - '502'
    image: modbus_master_image
    networks:
      icscommemulator:
        ipv4_address: 192.168.2.3
    volumes:
    - /tmp/ICSCommEmulator/masters/1/master.csv:/app/master.csv:ro
  modbus_slave_0:
    build:
      context: ./protocols/modbus/slave
      dockerfile: Dockerfile.slave
    container_name: modbus_slave_container_0
    environment:
    - PYTHONUNBUFFERED=1
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 10s
      test:
      - CMD-SHELL
      - test -f /app/app_running.lock
      timeout: 5s
    image: modbus_slave_image
    networks:
      icscommemulator:
        ipv4_address: 192.168.2.4
    volumes:
    - /tmp/ICSCommEmulator/slaves/0/slave.yaml:/app/slave.yaml:ro
  modbus_slave_1:
    build:
      context: ./protocols/modbus/slave
      dockerfile: Dockerfile.slave
    container_name: modbus_slave_container_1
    environment:
    - PYTHONUNBUFFERED=1
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 10s
      test:
      - CMD-SHELL
      - test -f /app/app_running.lock
      timeout: 5s
    image: modbus_slave_image
    networks:
      icscommemulator:
        ipv4_address: 192.168.2.5
    volumes:
    - /tmp/ICSCommEmulator/slaves/1/slave.yaml:/app/slave.yaml:ro
  modbus_slave_2:
    build:
      context: ./protocols/modbus/slave
      dockerfile: Dockerfile.slave
    container_name: modbus_slave_container_2
    environment:
    - PYTHONUNBUFFERED=1
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 10s
      test:
      - CMD-SHELL
      - test -f /app/app_running.lock
      timeout: 5s
    image: modbus_slave_image
    networks:
      icscommemulator:
        ipv4_address: 192.168.2.6
    volumes:
    - /tmp/ICSCommEmulator/slaves/2/slave.yaml:/app/slave.yaml:ro
  modbus_slave_3:
    build:
      context: ./protocols/modbus/slave
      dockerfile: Dockerfile.slave
    container_name: modbus_slave_container_3
    environment:
    - PYTHONUNBUFFERED=1
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 10s
      test:
      - CMD-SHELL
      - test -f /app/app_running.lock
      timeout: 5s
    image: modbus_slave_image
    networks:
      icscommemulator:
        ipv4_address: 192.168.2.7
    volumes:
    - /tmp/ICSCommEmulator/slaves/3/slave.yaml:/app/slave.yaml:ro
  modbus_slave_4:
    build:
      context: ./protocols/modbus/slave
      dockerfile: Dockerfile.slave
    container_name: modbus_slave_container_4
    environment:
    - PYTHONUNBUFFERED=1
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 10s
      test:
      - CMD-SHELL
      - test -f /app/app_running.lock
      timeout: 5s
    image: modbus_slave_image
    networks:
      icscommemulator:
        ipv4_address: 192.168.2.8
    volumes:
    - /tmp/ICSCommEmulator/slaves/4/slave.yaml:/app/slave.yaml:ro
