# Use an official Python runtime as a parent image
FROM python:3.10.0-alpine

# Set the working directory in the container to /app
WORKDIR /app

# Add the main script into the container at /app
COPY ./master.py /app

# Install any needed packages
RUN pip install --no-cache-dir pymodbus

# Run master.py when the container launches
ENTRYPOINT ["python", "master.py"]